force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Nome de Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/PercentComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentComplete__c</fullName>
    <label>Percent Complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Projetos__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

force-app/main/default/objects/Projetos__c/Projetos__c.object-meta.xml
<CustomObject>
    <label>Projetos</label>
    <nameField>
        <label>Nome de Projetos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projetos__c/fields/PercentComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentComplete__c</fullName>
    <label>Percent complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ProjectHandlerTest.cls
@isTest
private class ProjectHandlerTest {
    @isTest
    static void testRecalculateProject() {
        // Cria projeto
        Projetos__c proj = new Projetos__c(Name = 'Projeto Testado');
        insert proj;

        // Cria dois milestones com porcentagens diferentes
        Milestone__c m1 = new Milestone__c(Name = 'Marco A', Projeto__c = proj.Id, PercentComplete__c = 100);
        Milestone__c m2 = new Milestone__c(Name = 'Marco B', Projeto__c = proj.Id, PercentComplete__c = 0);
        insert new List<Milestone__c>{ m1, m2 };

        // Atualiza um milestone para disparar trigger
        m2.PercentComplete__c = 50;
        update m2;

        // Reconsulta projeto
        proj = [SELECT PercentComplete__c, Status__c FROM Projetos__c WHERE Id = :proj.Id];
        System.assertEquals(75, proj.PercentComplete__c);
        System.assertEquals('In Progress', proj.Status__c);
    }
}