force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Nome de Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/PercentComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentComplete__c</fullName>
    <label>Percent Complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Projetos__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

force-app/main/default/objects/Projetos__c/Projetos__c.object-meta.xml
<CustomObject>
    <label>Projetos</label>
    <nameField>
        <label>Nome de Projetos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projetos__c/fields/PercentComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentComplete__c</fullName>
    <label>Percent complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/ToDoItem__c.object-meta.xml
<CustomObject>
    <label>To-do Item</label>
    <nameField>
        <label>To-do  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-do Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do Item</relationshipLabel>
    <relationshipName>ToDoItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ToDoItemTriggerTest.cls
@isTest
private class ToDoItemTriggerTest {
    @isTest
    static void testToDoTriggerRuns() {
        // Cria Projeto
        Projetos__c proj = new Projetos__c(Name = 'Trigger Project');
        insert proj;

        // Cria Milestone
        Milestone__c milestone = new Milestone__c(Name = 'Trigger Milestone', Projeto__c = proj.Id);
        insert milestone;

        // Cria Tarefa (isso aciona a trigger ToDoItemTrigger)
        TodoItem__c todo = new TodoItem__c(Name = 'Trigger Task', Milestone__c = milestone.Id, Status__c = 'Completed');
        insert todo;

        // Verifica se Milestone foi atualizado
        milestone = [SELECT PercentComplete__c, Status__c FROM Milestone__c WHERE Id = :milestone.Id];
        System.assertEquals(100, milestone.PercentComplete__c);
        System.assertEquals('Complete', milestone.Status__c);
    }
}