force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Nome de Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Projetos__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

force-app/main/default/objects/Projetos__c/Projetos__c.object-meta.xml
<CustomObject>
    <label>Projetos</label>
    <nameField>
        <label>Nome de Projetos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDoItem__c/ToDoItem__c.object-meta.xml
<CustomObject>
    <label>To-do Item</label>
    <nameField>
        <label>To-do  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-do Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do Item</relationshipLabel>
    <relationshipName>ToDoItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectManagementController.cls
public with sharing class ProjectManagementController {
    @AuraEnabled
    public static Id createProject(String projectName) {
        Projetos__c project = new Projetos__c(Name = projectName);
        insert project;
        return project.Id;
    }
    
    @AuraEnabled
    public static Id createMilestone(String milestoneName, Id projectId) {
        Milestone__c milestone = new Milestone__c(Name = milestoneName, Projeto__c = projectId);
        insert milestone;
        return milestone.Id;
    }
    
    @AuraEnabled
    public static Id createTodo(String todoName, Id milestoneId) {
        TodoItem__c todo = new TodoItem__c(Name = todoName, Milestone__c = milestoneId);
        insert todo;
        return todo.Id;
    }
}